### ISSUE TITLE
Is it possible to use the narrator's natural voice

### ISSUE THREAD

**Issue by Leroy-X** [lesleyrs/tts-tui#1]
Is it possible to use the narrator's natural voice?
The system's built-in TTS is too mechanical, but the natural voice built into Win11 Narrator is more comfortable and natural
Thank you so much

**Comment by lesleyrs** [comment]
It's not possible to use the natural voices outside of Narrator for now.

It should be possible whenever you are able to select it as default voice in settings (not narrator settings) if that ever happens.
